connector:
  name: Github
  identifier: Github
  description:
  orgIdentifier: KD
  projectIdentifier: KD_CD_GitX
  type: Github
  spec:
    url: https://github.com/KapilDigani
    validationRepo: test
    authentication:
      type: Http
      spec:
        type: UsernameToken
        spec:
          username: KapilDigani
          tokenRef: account.KD_GitHub_Pwd
    apiAccess:
      type: Token
      spec:
        tokenRef: account.KD_GitHub_PAT
    executeOnDelegate: false
    type: Account
